version: '3'

services:
  wordpress:
    image: wordpress:php7.4
    ports:
      - "${WORDPRESS_PORT}:80"
    env_file: .env
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: .env
    ports:
      - ${DB_PORT}:3306
volumes:
  db_data: